name = "war-of-genesis-stats"
main = "src/index.js"
compatibility_date = "2026-10-01"

# `wrangler d1 create war-of-genesis-stats` 가 찍어 주는 database_id 를 아래에 넣는다.
[[d1_databases]]
binding = "DB"
database_name = "war-of-genesis-stats"
database_id = "6652a8b9-c5af-4c32-a0e9-3c4c86a175f3"
